import type { Metadata } from 'next';
import './globals.css';

import { ICategory } from '@/types';
import Header from '@/components/common/Header';
import { Provider } from '@/provider/Provider';
import { ReduxProvider } from '@/global/provider';
import { appwriteKeys } from '@/appwrite/environment';
import { ToastContainer } from 'react-toastify';
import { fetchDocuments } from '@/lib/apis/api';
import 'react-toastify/dist/ReactToastify.css';

export const revalidate = 86400;

export const metadata: Metadata = {
  title: 'iShop',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let categories: ICategory[] = [];

  try {
    categories = await fetchDocuments<ICategory>(
      appwriteKeys.DATABASE_ID,
      appwriteKeys.CATEGORIES_COLLECTION_ID
    );
  } catch (error) {
    console.error('Ошибка загрузки категорий:', error);
  }

  return (
    <html lang='en'>
      <body>
        <ReduxProvider>
          <ToastContainer />
          <Header categories={categories} />
          <Provider>{children}</Provider>
        </ReduxProvider>
      </body>
    </html>
  );
}
