import type { Metadata } from 'next';
import './globals.css';
import { Provider } from './provider/Provider';
import Header from './components/common/Header';
import { fetchDocuments } from '@/lib/api';
import { ICategory } from '@/types';

const DATABASE_ID = process.env.NEXT_PUBLIC_DATABASE_ID!;
const COLLECTION_ID = process.env.NEXT_PUBLIC_CATEGORIES_COLLECTION_ID!;

export const revalidate = 86400;

export const metadata: Metadata = {
  title: 'iShop',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let categories: ICategory[] = [];

  try {
    categories = await fetchDocuments<ICategory>(DATABASE_ID, COLLECTION_ID);
  } catch (error) {
    console.error('Ошибка загрузки категорий:', error);
  }

  return (
    <html lang='en'>
      <body>
        <Header categories={categories} />
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
