import type { Metadata } from 'next';
import 'antd/dist/reset.css';
import '../app/styles/globals.scss';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Providers } from '@/provider/AntProvider';
import { ICategory } from '@/common/types';
import { ReduxProvider } from '@/global/provider';
import { appwriteKeys } from '@/appwrite/environment';
import { ToastContainer } from 'react-toastify';
import { fetchDocuments } from '@/lib/apis/api';
import 'react-toastify/dist/ReactToastify.css';

import AntHeader from '@/common/components/header/Header';

export const revalidate = 86400;

export const metadata: Metadata = {
  title: 'iShop',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let categories: ICategory[] = [];

  try {
    categories = await fetchDocuments<ICategory>(
      appwriteKeys.DATABASE_ID,
      appwriteKeys.CATEGORIES_COLLECTION_ID
    );
  } catch (error) {
    console.error('Ошибка загрузки категорий:', error);
  }

  return (
    <html lang='en'>
      <body>
        <ReduxProvider>
          <Providers>
            <ToastContainer />
            <AntHeader categories={categories} />
            {children}
          </Providers>
        </ReduxProvider>
      </body>
    </html>
  );
}
