export const LABELS = {
  app: {
    title: 'CRM',
    footer: 'FOOTER',
    logout: 'Выйти',
  },
  menu: {
    categories: 'Категории',
    subCategories: 'Подкатегории',
    products: 'Товары',
    blogs: 'Блоги',
    references: 'Справочники',
    brands: 'Бренды',
    sizes: 'Размеры',
    colors: 'Цвета',
    tags: 'Теги',
  },
  buttons: {
    create: 'Создать',
    update: 'Обновить',
    delete: 'Удалить',
    filter: 'Фильтр',
    close: 'Закрыть',
    edit: 'Редактировать',
    add: 'Добавить',
    save: 'Сохранить',
  },
  fields: {
    name: 'Наименование',
    price: 'Цена',
    desc: 'Описание',
    group: 'Группа',
    brand: 'Бренд',
    image: 'Фото',
    attributes: 'Атрибуты',
    actions: 'Действия',
    quantity: 'Количество',
    color: 'Цвет',
    size: 'Размер',
    category: 'Категория',
    subCategory: 'Подкатегория',
    tags: 'Теги',
    title: 'Заголовок',
    content: 'Контент',
  },
  placeholders: {
    name: 'наименование',
    price: 'цена',
    desc: 'описание',
    group: 'группа',
    brand: 'бренд',
    selectCategory: 'Выберите категорию',
    selectColor: 'Выберите цвет',
    selectSize: 'Выберите размер',
    file: 'выберите файл',
  },
  pages: {
    product: 'Продукт',
    productsList: 'Список товаров',
    categories: 'Категории',
    subCategories: 'Группы',
    brands: 'Бренды',
    sizes: 'Размеры',
    colors: 'Цвета',
    tags: 'Теги',
    blogs: 'Блоги',
    references: 'Справочники',
  },
};
