export const appwriteKeys = {
  PROJECT_ID: process.env.NEXT_PUBLIC_PROJECT_ID!,
  DATABASE_ID: process.env.NEXT_PUBLIC_DATABASE_ID!,
  CATEGORIES_COLLECTION_ID: process.env.NEXT_PUBLIC_CATEGORIES_COLLECTION_ID!,
  SUBCATEGORIES_COLLECTION_ID:
    process.env.NEXT_PUBLIC_SUBCATEGORIES_COLLECTION_ID!,
  PRODUCTS_COLLECTION_ID: process.env.NEXT_PUBLIC_PRODUCTS_COLLECTION_ID!,
  ATTRIBUTES_COLLECTION_ID: process.env.NEXT_PUBLIC_ATTRIBUTES_COLLECTION_ID!,
  ENDPOINT: process.env.NEXT_PUBLIC_ENDPOINT!,
} as const;
