export const appwriteKeys = {
  PROJECT_ID: process.env.NEXT_PUBLIC_PROJECT_ID!,
  DATABASE_ID: process.env.NEXT_PUBLIC_DATABASE_ID!,
  CATEGORIES_COLLECTION_ID: process.env.NEXT_PUBLIC_CATEGORIES_COLLECTION_ID!,
  SUBCATEGORIES_COLLECTION_ID:
    process.env.NEXT_PUBLIC_SUBCATEGORIES_COLLECTION_ID!,
  PRODUCTS_COLLECTION_ID: process.env.NEXT_PUBLIC_PRODUCTS_COLLECTION_ID!,
  ATTRIBUTES_COLLECTION_ID: process.env.NEXT_PUBLIC_ATTRIBUTES_COLLECTION_ID!,
  ENDPOINT: process.env.NEXT_PUBLIC_ENDPOINT!,
  CART_ID: process.env.NEXT_PUBCLIC_CART_COLLECTION_ID!,
  CART_ITEM_ID: process.env.NEXT_PUBLIC_CART_ITEM_COLLECTION_ID!,
  BLOG_ID: process.env.NEXT_PUBLIC_BLOG_COLLECTION_ID!,
  FAVORITES_ID: process.env.NEXT_PUBLIC_FAVORITES_COLLECTION_ID!,
} as const;
