export const shoes = [
  {
    category: 'shoes',
    subcategory: 'sneakers',
    id: 1,
    name: 'Nike Court Zoom Cage 2',
    price: '4699',
    image: '/assets/1sneaker.png',
  },
  {
    category: 'shoes',
    subcategory: 'sneakers',
    id: 2,
    name: 'Air Force 1 Ultra',
    price: '3000',
    image: '/assets/2sneaker.png',
  },
  {
    category: 'shoes',
    subcategory: 'sneakers',
    id: 3,
    name: 'Air Force 1 Ultra Flyknit',
    price: '4700',
    image: '/assets/3sneaker.png',
  },
  {
    category: 'shoes',
    subcategory: 'sneakers',
    id: 4,
    name: 'Men’s Soccer Shoes',
    price: '3500',
    image: '/assets/4sneaker.png',
  },
  {
    category: 'shoes',
    subcategory: 'sneakers',
    id: 5,
    name: 'Air Force 1 Ultra Flyknit',
    price: '5000',
    image: '/assets/3sneaker.png',
  },
];
