export const ConfigRoutes = {
  HOME: '/',
  CATEGORIES: '/categories',
  SUB_CATEGORIES: '/sub-categories',
  SUB_CATEGORY_DETAILS: '/sub-categories-details/:id?',
  BLOGS: '/blogs',
  BLOG_DETAILS_PATH: '/blog-details/:id',
  BLOG_DETAILS_GET: (id: string) => `/blog-details/${id}`,
  BLOG_CREATE: '/blog-details',
  PRODUCTS: '/products',
  PRODUCT_DETAILS_PATH: '/product-details/:id?',
  PRODUCT_DETAILS_GET: (id: string) => `/product-details/${id}`,
  PRODUCT_CREATE: '/product-details',
  REFERENCE_BRANDS: '/reference/brands',
  REFERENCE_SIZES: '/reference/sizes',
  REFERENCE_COLORS: '/reference/colors',
  REFERENCE_TAGS: '/reference/tags',
  BANNERS: '/banners',
  BANNER_DETAILS_PATH: '/banner-details/:id?',
  BANNER_DETAILS_GET: (id: string) => `/banner-details/${id}`,
  BANNER_CREATE: '/banner-details',
};
